[package]
name = "process-utils"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, optional = true, features = ["process"] }

[features]
default = ["tokio"]
tokio = ["dep:tokio"]
