[package]
name = "bytes-util"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bytes = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
