[package]
name = "expgolomb"
version = "0.1.1"
edition.workspace = true
license.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }


[dependencies]
bytes-util = { path = "../bytes-util" }

[dev-dependencies]
bytes = { workspace = true }
