[package]
name = "aac"
version = "0.1.1"
edition.workspace = true
license.workspace = true

[dependencies]
bytes-util = { path = "../bytes-util" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
